apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reliantflow
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - reliantflow

  selector:
    matchLabels:
      app: reliantflow

  endpoints:
    - port: http
      path: /metrics
      interval: 15s